services:

  # Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run
    env_file:
      - docker.env
    networks:
      - internal_network
      - external_network

  # A load balancer to enable non-disruptive replacement of web containers
  lb:
    image: nginxproxy/nginx-proxy:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-custom.conf:/etc/nginx/conf.d/nginx-custom.conf:ro
    networks:
      - internal_network

  web:
    image: ghcr.io/huideyeren/misskey:latest
    restart: always
    links:
      - db
      - redis
      - mcaptcha
      - meilisearch
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    #ports: ["3000:3000"]  # enable this if you want to access directly
    networks:
      - internal_network
      - external_network
    volumes:
      - ./misskey-default.yml:/misskey/.config/default.yml:ro
    environment:
      - VIRTUAL_HOST=test.inokashiraskey.jp
      #- VIRTUAL_HOST=~^.*$$  # marker for lb
      #- VIRTUAL_PORT=3000  # target port for lb

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - /var/misskey/redis-data:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:15-alpine
    networks:
      - internal_network
    env_file:
      - docker.env
    volumes:
      - ./pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql:ro
      - /var/misskey/db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

  mcaptcha:
    restart: always
    image: mcaptcha/mcaptcha:latest
    networks:
      internal_network:
      external_network:
        aliases:
          - localhost
    ports:
      - 7493:7493
    env_file:
      - ./docker.env
    environment:
      PORT: 7493
      MCAPTCHA_redis_URL: "redis://mcaptcha_redis/"
    depends_on:
      db:
        condition: service_healthy
      mcaptcha_redis:
        condition: service_healthy

  mcaptcha_redis:
    image: mcaptcha/cache:latest
    networks:
      - internal_network
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  meilisearch:
    restart: always
    image: getmeili/meilisearch:v1.3.4
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    env_file:
      - ./meilisearch.env
    networks:
      - internal_network
    volumes:
      - ./meili_data:/meili_data

  wasabi-proxy:
    restart: always
    image: nginx
    volumes:
      - ./wasabi.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - internal_network
      - external_network
    environment:
      - VIRTUAL_HOST=test-storage.inokashiraskey.jp

networks:
  internal_network:
    internal: true
  external_network:
