services:

  # # Cloudflare Tunnel
  # tunnel:
  #   image: cloudflare/cloudflared:latest
  #   restart: always
  #   command: tunnel --no-autoupdate run
  #   env_file:
  #     - docker.env
  #   networks:
  #     - internal_network
  #     - external_network

  # # A load balancer to enable non-disruptive replacement of web containers
  # lb:
  #   image: nginxproxy/nginx-proxy:latest
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./nginx-custom.conf:/etc/nginx/conf.d/nginx-custom.conf:ro
  #   networks:
  #     - internal_network

  web:
    image: huideyeren/misskey:latest
    restart: always
    links:
      - db
      - redis
      - mcaptcha
      - meilisearch
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports: ["3000:3000"]  # enable this if you want to access directly
    networks:
      - internal_network
      - external_network
    volumes:
      - ./misskey-default.yml:/misskey/.config/default.yml:ro
    # environment:
      #- VIRTUAL_HOST=~^.*$$  # marker for lb
      #- VIRTUAL_PORT=3000  # target port for lb
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - redis-data:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

  db:
    restart: always
    image: postgres:16
    networks:
      - internal_network
    env_file:
      - docker.env
    volumes:
      - ./pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql:ro
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

  mcaptcha:
    restart: always
    image: mcaptcha/mcaptcha:latest
    networks:
      internal_network:
      external_network:
        aliases:
          - localhost
    ports:
      - 7493:7493
    env_file:
      - ./mcaptcha.env
    environment:
      PORT: 7493
    depends_on:
      db:
        condition: service_healthy
      mcaptcha_redis:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

  mcaptcha_redis:
    image: mcaptcha/cache:latest
    networks:
      - internal_network
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

  meilisearch:
    restart: always
    image: getmeili/meilisearch:v1.3.4
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    env_file:
      - ./meilisearch.env
    networks:
      - internal_network
    volumes:
      - meili_data:/meili_data
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

volumes:
  db-data:
  redis-data:
  meili_data:
  mcaptcha-data:

networks:
  internal_network:
    internal: true
  external_network:
